### ISSUE TITLE
ACCESS DENIED

### ISSUE THREAD

**Issue by Duts** [mysoncaby/skybook#1]
Why do you have these credentials?

**Comment by mysoncaby** [comment]
Hello
Who are you?
This is my own project

I dont understand your idea

**Comment by Duts** [comment]
Ok, do you work for Raffaello or what?

**Comment by mysoncaby** [comment]
I know raffaello
But this is not raffaello project

**Comment by Duts** [comment]
Ok, but why did you have the folders and the credential of this site?

**Comment by mysoncaby** [comment]
what site do  you mean?
Please send me link

**Comment by Duts** [comment]
https://github.com/mysoncaby/Booking-Online-in-Laravel/blob/d67d170da8e45c26954c5533d6a73cb051830a1c/resources/views/customer/onlocation/raffaello-sandbox.com/public_html/enstabish.txt

**Comment by mysoncaby** [comment]
Now, I am working on that site
and this is not raffaello project.
that is my issue.
That is unexpected file
I will remove this repository

**Comment by Duts** [comment]
Perfect! Pay attention, this file can compromise that site!

**Comment by mysoncaby** [comment]
Dear

Thank you very much
I just deleted local git repository
Thanks again
